menu_app/urls.py
from django.urls import path
from menu_app import views

app_name = 'menu_app'

urlpatterns = [
    path('menu/', views.index, name='menu'),
    path('category/<int:category_id>/', views.category_by_products_view, name='category'),
    path('product/<int:product_id>/', views.product_detail, name='product'),
    path('cart/', views.view_cart, name='cart'),
    path('orders_list/', views.wish_list_view, name='orders_list'),
    path('register/', views.register_view, name='register'),
    # path('login/', views.login_user_view, name='login'),

    path('add_item/<int:product_id>/', views.AddToCartView.as_view(), name='add_item'),
    path('remove_item/<int:product_id>/', views.DeleteItemAPIView.as_view(), name='remove_item'),
    path('update_item/<int:product_id>/', views.UpdateItemAPIView.as_view(), name='update_item'),
    path('finalize_order/', views.FinalizeOrderAPIView.as_view(), name='finalize_order')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from menu_app.views import ProductViewSet, CustomerViewSet, OrderViewSet
from django.conf import settings
from django.conf.urls.static import static

router = DefaultRouter()
router.register(r'products', ProductViewSet, basename='product')
router.register(r'customers', CustomerViewSet, basename='customer')
router.register(r'orders', OrderViewSet, basename='order')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('menu_app.urls')),
    path('api/', include(router.urls))
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

menu_app/models.py
from django.db import models
from decimal import Decimal

class Category(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='categorys/', blank=True, null=True)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'

class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    image = models.ImageField(upload_to='products/', blank=True, null=True)
    
    category = models.ForeignKey(
        Category, related_name='products', on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'

class Customer(models.Model):
    name = models.CharField(max_length=255)
    number = models.CharField(max_length=15)
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'
    
class Order(models.Model):
    
    STATUS_CHOICES = [
        ('pendente', 'Pendente'),
        ('producao', 'Produção'),
        ('enviado', 'Enviado'),
        ('concluido', 'Concluido'),
    ]

    customer = models.ForeignKey(
        Customer, on_delete=models.CASCADE, related_name='pedidos'
    )
    total = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal("0.0"))
    status = models.CharField(
        max_length=20, choices=STATUS_CHOICES, default='pendente'
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Pedido: {self.pk} - {self.customer.name}'
    
    class Meta:
        verbose_name = 'Pedido'
        verbose_name_plural = 'Pedidos'


class OrderProduct(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='order_products')
    quantity = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f'{self.product.name} x {self.quantity}'
    
    class Meta:
        verbose_name = 'Produto no pedido'
        verbose_name_plural = 'Produtos no pedido'

menu_app/forms.py
from django import forms 
from .models import Customer

class LoginForm(forms.ModelForm):
    number = forms.CharField(
        widget=forms.TextInput(attrs={
            'class': 'form-control'
        })
    )
    
    class Meta:
        model = Customer
        fields = ['number']

    

menu_app/views/menu_api.py
from rest_framework.viewsets import ModelViewSet, ViewSet
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from django.db import transaction
from django.shortcuts import render, redirect, get_object_or_404
from django.template.response import TemplateResponse
from django.contrib import messages
from django.shortcuts import redirect
from menu_app.models import Customer, Product, Order, OrderProduct
from menu_app.serializers import (CustomerSerializer, 
ProductSerializer, OrderSerializer)
from decimal import Decimal
import json

# Define a visualização da API para o modelo Customer
class CustomerViewSet(ModelViewSet):
    # Define a queryset (conjunto de objetos) que será retornado pela view
    queryset = Customer.objects.all()  # Recupera todos os objetos do modelo Customer
    # Define o serializer que será usado para transformar os dados do modelo em formato JSON e vice-versa
    serializer_class = CustomerSerializer  # Utiliza o CustomerSerializer para serializar os dados

# Define a visualização da API para o modelo Product
class ProductViewSet(ModelViewSet):
    # Define a queryset (conjunto de objetos) que será retornado pela view
    queryset = Product.objects.all()  # Recupera todos os objetos do modelo Product
    # Define o serializer que será usado para transformar os dados do modelo em formato JSON e vice-versa
    serializer_class = ProductSerializer  # Utiliza o ProductSerializer para serializar os dados

# Define a visualização da API para o modelo Order
class OrderViewSet(ModelViewSet):
    # Define a queryset (conjunto de objetos) que será retornado pela view
    queryset = Order.objects.all()  # Recupera todos os objetos do modelo Order
    # Define o serializer que será usado para transformar os dados do modelo em formato JSON e vice-versa
    serializer_class = OrderSerializer  # Utiliza o OrderSerializer para serializar os dados

class AddToCartView(APIView):
    """
    View para adicionar itens no carrinho
    """
    def post(self, request, product_id):
        # Obter o produto pelo ID
        product = get_object_or_404(Product, pk=product_id)
        
        # Obter a quantidade do corpo da requisição, padrão = 1
        quantity = int(request.data.get('quantity', 1))
        
        # Obter o carrinho da sessão
        cart = request.session.get('cart', {})
        
        # Adicionar ou atualizar o produto no carrinho
        if str(product.pk) in cart:
            cart[str(product.pk)]['quantity'] += quantity
        else:
            cart[str(product.pk)] = {
                'name': product.name,
                'price': str(product.price),
                'quantity': quantity,
                'image': product.image.url if product.image else '',
            }
        
        # Atualizar o carrinho na sessão
        request.session['cart'] = cart
        
        return redirect('menu_app:cart')

class DeleteItemAPIView(APIView):
    """
    APIView para remover um item do carrinho.
    """
    def post(self, request, product_id):
        # Obtém o carrinho armazenado na sessão. Se não houver, inicializa como um dicionário vazio.
        cart = request.session.get('cart', {})

        # Verifica se o produto identificado pelo 'product_id' existe no carrinho.
        if str(product_id) in cart:
            # Remove o item do carrinho utilizando sua chave (product_id).
            del cart[str(product_id)]
            # Atualiza o carrinho na sessão com a nova lista de itens (sem o item removido).
            request.session['cart'] = cart
            return Response({'message': 'Item Removido com sucesso'}, status=status.HTTP_200_OK)

        # Se o item não estiver no carrinho, retorna um erro.
        return Response(
            {'error': 'Item não encontrado no carrinho'}, 
            status=status.HTTP_404_NOT_FOUND
        )

class UpdateItemAPIView(APIView):
    """
    APIView para atualizar a quantidade de um produto no carrinho.
    Permite aumentar ou diminuir a quantidade.
    """
    def post(self, request, product_id):
        try:
            # Tenta carregar os dados do corpo da requisição como JSON
            data = request.data
            action = data.get('action')  # Obtém o valor de 'action'
        except json.JSONDecodeError:
            # Retorna erro se houver falha ao processar o JSON
            return Response({'error': 'Erro ao processar JSON'}, status=status.HTTP_400_BAD_REQUEST)

        # Obtém o carrinho da sessão, ou inicializa como um dicionário vazio
        cart = request.session.get('cart', {})

        # Verifica se o produto existe no carrinho
        if str(product_id) in cart:
            # Se a ação for 'increase', aumenta a quantidade
            if action == 'increase':
                cart[str(product_id)]['quantity'] += 1
            # Se a ação for 'decrease', diminui a quantidade, respeitando o limite mínimo de 1
            elif action == 'decrease':
                if cart[str(product_id)]['quantity'] > 1:
                    cart[str(product_id)]['quantity'] -= 1
                else:
                    return Response({'error': 'A quantidade mínima é 1'}, status=status.HTTP_400_BAD_REQUEST)
        else:
            # Retorna erro se o produto não for encontrado
            return Response({'error': 'Produto não encontrado no carrinho'}, status=status.HTTP_404_NOT_FOUND)

        # Atualiza o carrinho na sessão com as alterações feitas
        request.session['cart'] = cart
        request.session.modified = True

        # Calcula os valores necessários
        quantity = cart[str(product_id)]['quantity']
        subtotal = float(cart[str(product_id)]['price']) * quantity
        total = sum(float(item['price']) * item['quantity'] for item in cart.values())

        # Retorna as informações atualizadas
        return Response({
            'subtotal': subtotal,
            'total': total,
            'quantity': quantity
        }, status=status.HTTP_200_OK)
    
class FinalizeOrderAPIView(APIView):
    """
    API para finalizar o pedido com os itens do carrinho.
    Cria um pedido com os produtos, quantidades e total.
    """
    def post(self, request):
        # Obtém o carrinho armazenado na sessão
        cart = request.session.get('cart', {})

        # Verifica se o carrinho está vazio
        if not cart:
            return Response({'error': 'O carrinho está vazio'}, status=status.HTTP_400_BAD_REQUEST)

        # Inicializa o total do pedido
        total = 0

        try:
            # Cria o pedido em uma transação atômica
            with transaction.atomic():

                customer = Customer.objects.get(pk=1)
                # customer = get_object_or_404(Customer, pk=customer_id)

                # Cria o objeto do pedido
                order = Order.objects.create(
                    customer = customer
                )

                # Itera pelos itens do carrinho para criar OrderItems
                for product_id, item in cart.items():
                    product = Product.objects.get(pk=product_id)  # Obtém o produto do banco
                    quantity = item['quantity']
                    price = float(item['price'])

                    # Cria um item do pedido
                    OrderProduct.objects.create(
                        order=order,
                        product=product,
                        quantity=quantity,
                        price=price,
                    )

                    # Incrementa o total do pedido
                    total += price * quantity

                # Atualiza o total do pedido
                order.total = Decimal(str(total))
                order.save()

                # Limpa o carrinho da sessão
                request.session['cart'] = {}
                request.session.modified = True

            # Retorna a resposta de sucesso
            return Response({
                'message': 'Pedido finalizado com sucesso!',
                'order_id': order.pk,
                'total': f'{total:.2f}',
                'customer': customer.pk
            }, status=status.HTTP_201_CREATED)

        except Product.DoesNotExist:
            return Response({'error': 'Um dos produtos do carrinho não foi encontrado'}, status=status.HTTP_404_NOT_FOUND)
        except Exception as e:
            return Response({'error': str(e)}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

menu_app/views/menu_view.py
from django.shortcuts import render, get_object_or_404, redirect
from menu_app.models import Category, Product, OrderProduct, Order, Customer
from django.contrib.auth import login, authenticate

def index(request):
    # Obtém todas as categorias do banco de dados usando o modelo Category.
    categorys = Category.objects.all()
    
    # Cria um dicionário de contexto com as categorias, para enviar para o template.
    context = {
        'categorys': categorys  # Passa as categorias para serem exibidas no template.
    }
    
    # Renderiza o template 'index.html', passando o contexto com as categorias.
    return render(request, 'index.html', context)


def category_by_products_view(request, category_id):
    # Tenta obter uma categoria específica pelo ID fornecido.
    # Se a categoria não for encontrada, retorna uma página 404.
    category = get_object_or_404(Category, pk=category_id)
    
    # Filtra os produtos que pertencem à categoria selecionada.
    products = Product.objects.filter(category=category_id)
    
    # Cria um dicionário de contexto com os produtos e a categoria para enviar ao template.
    context = {
        'products': products,  # Lista de produtos da categoria selecionada.
        'category': category   # Detalhes da categoria selecionada.
    }
    
    # Renderiza o template 'products.html', passando o contexto com os produtos e a categoria.
    return render(request, 'products.html', context)


def product_detail(request, product_id):
    # Tenta obter um produto específico pelo ID fornecido.
    # Se o produto não for encontrado, retorna uma página 404.
    product = get_object_or_404(Product, pk=product_id)
    
    # Cria um dicionário de contexto com o produto para enviar ao template.
    context = {
        'product': product  # Detalhes do produto selecionado.
    }
    
    # Renderiza o template 'product.html', passando o contexto com os detalhes do produto.
    return render(request, 'product.html', context)


def view_cart(request):
    # Obtém o carrinho armazenado na sessão. Se não houver, inicializa como um dicionário vazio.
    cart = request.session.get('cart', {})

    # Calcula o valor total do carrinho.
    total = 0
    for item in cart.values():
        # Para cada item no carrinho, multiplica o preço pela quantidade e soma ao total.
        total += float(item['price']) * item['quantity']

    # Prepara o contexto com o carrinho e o total calculado para enviar ao template.
    context = {
        'cart': cart,  # Carrinho com os itens e suas informações.
        'total': total  # Total acumulado do carrinho.
    }

    # Renderiza o template 'cart.html', passando o contexto com os dados do carrinho.
    return render(request, 'cart.html', context)

def wish_list_view(request):

    customer = Customer.objects.get(pk=1)

    orders = Order.objects.filter(
        customer=customer).prefetch_related('order_products__product')
    
    context = {
        'orders': orders
    }
    
    return render(request, 'wish_list.html', context)

def register_view(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        number = request.POST.get('number')
    
        user = Customer.objects.create(name=name, number=number)
        user.save()

    return render(request, 'register.html')
        

# def login_view(request):
#     if request.method == 'POST':
#         phone = request.POST.get('phone')
#         user = Customer.objects.get(number=phone)

#         # if not user:
#         #     print("usurio não cadastrado")
#         # else:
#         #      ...



#     return render(request, 'index.html')

menu_app/templates/cart.html
{% extends "base.html" %}
{% load static %}
{% load custom_filters %}
{% block main_content %}
<div class="container my-5">
    <h1 class="text-center mb-4">Carrinho de Compras</h1>
    {% if cart %}
        <table class="table table-bordered text-center">
            <thead class="table-dark">
                <tr>
                    <th>Imagem</th>
                    <th>Produto</th>
                    <th>Preço Unitário</th>
                    <th>Quantidade</th>
                    <th>Subtotal</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                {% for product_id, item in cart.items %}
                <tr>
                    <td><img src="{{ item.image }}" alt="{{ item.name }}" class="cart-image"></td>
                    <td>{{ item.name }}</td>
                    <td>R$ {{ item.price }}</td>
                    <td>
                        <div class="d-flex justify-content-center align-items-center">
                            <button class="btn btn-outline-danger btn-sm update-cart" data-action="decrease" data-product-id="{{product_id}}">-</button>
                            <span class="mx-2" id="quantity-{{product_id}}">{{ item.quantity }}</span>
                            <button class="btn btn-outline-success btn-sm update-cart" data-action="increase" data-product-id="{{product_id}}" >+</button>
                        </div>
                    </td>
                    <td id="subtotal-{{product_id}}">R$ {{ item.price|multiply:item.quantity|floatformat:2}}</td>
                    <td>
                        <form id="removeToItemCartForm" action="{% url "menu_app:remove_item" product_id %}" method="POST">
                            {% csrf_token %}
                            <button productId="{{product_id}}" type="submit" class="btn btn-danger btn-sm remove-btn">Remover</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="4" class="text-end"><strong>Total:</strong></td>
                    <td colspan="2"><strong id='total'>R$ {{ total|floatformat:2 }}</strong></td>
                </tr>
            </tfoot>
        </table>
        <div class="d-flex justify-content-end">
            <form action="" method="POST">
                {% csrf_token %}
                <button confirmAuthentication="{{user.is_authenticated}}" id="finalizeOrder" type="submit" class="btn btn-primary">Finalizar Compra</button>
            </form>
        </div>
    {% else %}
        <div class="alert alert-warning text-center">
            Seu carrinho está vazio. <a href="{% url 'menu_app:menu' %}" class="alert-link">Voltar ao menu</a>
        </div>
    {% endif %}
</div>
<!-- Modals -->
<div class="modal fade" id="removeToCartModal" tabindex="-1" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fechar"></button>
            </div>
            <div class="modal-body modal-content-info">
                <img class="img-add-to-cart" src="{% static "assets/images/depressao.png" %}">
                <strong>Tem certeza que deseja remover do carrinho?</strong>
            </div>
            <div class="modal-footer">
                <button type="button" id="noRemove" class="btn btn-primary">Não</button>
                <button type="button" id="confirmRemove" class="btn btn-secondary">Sim, remover</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="loginUser" tabindex="-1" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content modal-ajust">
            <div class='top-form-register'>
                <img class="logo-register" src="https://image.freepik.com/vetores-gratis/exterior-da-loja-generica-na-rua-da-cidade_169241-1064.jpg" alt="Loja Generica">
                <p><b>Ainda não tem cadastro?</b> <br> Acesse sua conta informando <br> seu telefone ou cadastre-se</p>
            </div>
            <div>
                <form class="login-form" action="" method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="fieldPhone" class="form-label">Talefone</label>
                        <input id='fieldPhone' type="text" name="phone" class="form-control">
                    </div>
                    <div class="container-login-btn">
                        <button class="login-btn btn btn-primary">Login</button>
                    </div>
                </form>
                <a href="{% url "menu_app:register" %}" class="register-link">Criar Cadastro</a>
            </div>  
        </div>
    </div>
</div>
<script>
    const csrfToken = '{{ csrf_token }}'
</script>
{% endblock main_content %}

menu_app/templates/index.html
{% extends "base.html" %}
{% block main_content %}
<div class="d-flex justify-content-between align-items-center mb-4">
    <h2>Cárdapio</h2>
</div>
<div class="row">
    {% for category in categorys %}
        <div class="col-md-4 mb-4">
            <a class="access" href="{% url "menu_app:category" category.id %}">
                <div class="card category">
                    <img class="image-products" src="{{category.image.url}}" class="card-img-top" alt="{{product.image.name}}">
                    <div class="card-body name-category">
                        <h5 class="card-title">{{category.name}}</h5>
                    </div>
                </div>
            </a>
        </div>
    {% endfor %}
</div>
{% endblock main_content %}

menu_app/templates/product.html
{% extends "base.html" %}
{% load static %}
{% block main_content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6">
            <img src="{{ product.image.url }}" alt="{{ product.name }}" class="img-fluid product-image image-specific">
        </div>
        <div class="col-md-6">
            <h1>{{ product.name }}</h1>
            <p><strong>Descrição:</strong> {{ product.description }}</p>
            <p id="priceProduct" data-price="{{product.price}}"><strong>Preço:</strong> R$ {{ product.price }}</p>

            <div class="mb-4">
                <label for="quantity" class="form-label">Quantidade:</label>
                <div class="input-group">
                    <button class="btn btn-outline-secondary" id="decrease" type="button">-</button>
                    <input type="text" id="quantity" name="quantity" class="form-control" value="1" min="1">
                    <button class="btn btn-outline-secondary" id="increase" type="button">+</button>
                </div>
            </div>

            <div class="mb-4">
                <p><strong>Total: </strong>R$ <span id="total-price">{{ product.price }}</span></p>
            </div>

            <!-- Formulário de adicionar ao pedido -->
            <form id="addToCartForm" action="{% url "menu_app:add_item" product.id %}" method="POST">
                {% csrf_token %}
                <input type="hidden" id="final-quantity" name="quantity" value="1">
                <button onclick="addItemToCart()" id="addToCartBtn" type="submit" class="btn btn-primary">Adicionar ao Pedido</button>
            </form>
        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="addToCartModal" tabindex="-1" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fechar"></button>
            </div>
            <div class="modal-body modal-content-info">
                <img class="img-add-to-cart" src="{% static "assets/images/comemoração.png" %}">
                <strong>{{product.name}} Adicionado ao carrinho</strong>
            </div>
            <div class="modal-footer">
                <a href="{% url "menu_app:menu" %}" class="btn btn-secondary">Continuar Comprando</a>
                <a href="{% url "menu_app:cart" %}" class="btn btn-primary">Ir para o carrinho</a>
            </div>
        </div>
    </div>
</div>
{% endblock main_content %}

menu_app/templates/products.html
{% extends "base.html" %}
{% block main_content %}
<div class="container mt-5">
    <h1 class="mb-4">{{category.name}}</h1>
    <div class="row row-cols-2 row-cols-md-4 g-4">
        {% for product in products %}
        <div class="col">
            <div class="card text-center">
                <img class="image-products" src="{{ product.image.url }}" alt="{{ product.name }}" class="card-img-top product-image mx-auto mt-3">
                <a class="access" href="{% url "menu_app:product" product.id %}">
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <p class="card-text text-muted">{{ product.description|truncatechars:20 }}</p>
                        <p class="text-primary fw-bold">R$ {{ product.price }}</p>
                    </div>
                </a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock main_content %}

menu_app/templates/register.html
{% extends "base.html" %}
{% load static %}
{% block main_content %}

<div class="content-center">
    <div class='conteiner-register'>
        <div class='top-form-register'>
            <img class="logo-register" src="https://image.freepik.com/vetores-gratis/exterior-da-loja-generica-na-rua-da-cidade_169241-1064.jpg" alt="Loja Generica">
            <p>Cadastre-se para continuar comprando</p>

        </div>
        <div class="mb-3">
            <form class="row g-3 needs-validation" method="POST" action="{% url "menu_app:register" %}">
                {% csrf_token %}
                <div class="mb-3 position-relative">
                    <label for="name" class="form-label">Nome</label>
                    <input id="name" type="text", name='name' class="form-control">
                </div>
                <div class="mb-3 position-relative">
                    <label for="number" class="form-label">Telefone</label>
                    <input id="number" type="text", name='number' class="form-control">
                </div>
                <button type="submit" class="btn btn-primary">Registrar</button>
            </form>
        </div>
    </div>
</div>

{% endblock main_content %}

menu_app/templates/wish_list.html
{% extends "base.html" %}
{% block main_content %}
<h1>LISTA DE TAREFAS</h1>
{% endblock main_content %}